### ISSUE TITLE
Document the changes with regards to the original package

### ISSUE THREAD

**Issue by Louies89** [ratson/react-native-recyclerview-list-android#1]
@ratson 
Hi,
Could you please let me know what are the changes you have done with compression to the original package?

And what are the enhancements you have done?

Thank you :)

**Comment by ratson** [comment]
Here are the list of changes https://github.com/ratson/react-native-recyclerview-list-android/compare/66df1b0ea013122b6bc3f2c04713e35f85df5420...master

**Comment by Louies89** [comment]
Hi, I understand you have made some changes and I am able to compare and check the changes, but my question was not about what code changes you have done, it is about, what enhancements you have done, compare to the master branch one. 
For Example:
```
1>> Lint warnings are suppressed.
2>> Animating file was not doing anything, so removed it.
3>> ViewProps is the latest from RN, so added it.
4>> move up is not necessary due to "XXX, YYY & ZZZ reasons", so removed it..
```

Could make a list like this?
